### ISSUE TITLE
GitHub Search Option

### ISSUE THREAD

**Issue by andriemc** [bedantadey17/unifsearch-extension#1]
Allow people to search using GitHub.

`%s` should be replaced with the search query.

Search String: `https://github.com/search?q=%s`

**Comment by andriemc** [comment]
Made a pr #2

**Comment by andriemc** [comment]
This should be closed if/once pr is merged. Or it can be closed as not planned.

**Comment by bedantadey17** [comment]
merged. thank you for your input.
